import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join as joinPath } from "node:path";
import {
  renderLeakReportHtml,
  writeLeakReportHtml,
  type LeakReportSectionType,
} from "./leakReport.js";

let workDir: string;

beforeEach(() => {
  workDir = mkdtempSync(joinPath(tmpdir(), "mdt-leakreport-"));
});

afterEach(() => {
  rmSync(workDir, { recursive: true, force: true });
});

function makeSection(overrides: Partial<LeakReportSectionType> = {}): LeakReportSectionType {
  return {
    title: "DemoTests/DemoCase/testThing",
    passed: true,
    totals: { baselineLeaks: 0, afterLeaks: 0, leakDelta: 0 },
    newCycles: [],
    steps: ["$ xcodebuild ..."],
    ...overrides,
  };
}

describe("renderLeakReportHtml", () => {
  it("renders a passing report with PASS pill and 'no new cycles' message", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [makeSection()],
    });
    expect(html).toContain("<!doctype html>");
    expect(html).toContain('class="verdict pass">PASS');
    expect(html).toContain("No new ROOT CYCLEs after the test.");
  });

  it("renders a failing section with FAIL pill and failureReason", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          passed: false,
          failureReason: "1 new leak: BadViewModel",
          newCycles: [
            { rootClass: "BadViewModel", chainLength: 4, allowlisted: false },
          ],
        }),
      ],
    });
    expect(html).toContain('class="verdict fail">FAIL');
    expect(html).toContain("1 new leak: BadViewModel");
    expect(html).toContain("BadViewModel");
    expect(html).toContain('class="badge fail">new leak');
  });

  it("marks allowlisted cycles with the allowlist badge", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          passed: false,
          newCycles: [
            { rootClass: "SwiftUI.Internal", chainLength: 2, allowlisted: true },
          ],
        }),
      ],
    });
    expect(html).toContain('class="badge allow">allowlisted');
  });

  it("escapes HTML in class names and titles to prevent injection", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          title: "<script>alert(1)</script>",
          newCycles: [
            {
              rootClass: '<img onerror="x" src="y">',
              chainLength: 1,
              allowlisted: false,
            },
          ],
        }),
      ],
    });
    expect(html).not.toContain("<script>alert(1)");
    expect(html).not.toContain('<img onerror="x"');
    expect(html).toContain("&lt;script&gt;");
    expect(html).toContain("&lt;img onerror=&quot;x&quot;");
  });

  it("includes baseline + after memgraph paths when provided", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          baselineMemgraph: "/tmp/a.memgraph",
          afterMemgraph: "/tmp/b.memgraph",
        }),
      ],
    });
    expect(html).toContain("/tmp/a.memgraph");
    expect(html).toContain("/tmp/b.memgraph");
    expect(html).toContain("Baseline:");
    expect(html).toContain("After:");
  });

  it("renders the steps log inside a collapsed details block", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [makeSection({ steps: ["step 1", "step 2", "step 3"] })],
    });
    expect(html).toContain("<details>");
    expect(html).toContain("Run log (3 steps)");
    expect(html).toContain("step 1");
  });

  it("renders multiple sections in order", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({ title: "Alpha" }),
        makeSection({ title: "Beta" }),
        makeSection({ title: "Gamma" }),
      ],
    });
    const alphaIdx = html.indexOf("Alpha");
    const betaIdx = html.indexOf("Beta");
    const gammaIdx = html.indexOf("Gamma");
    expect(alphaIdx).toBeGreaterThan(-1);
    expect(betaIdx).toBeGreaterThan(alphaIdx);
    expect(gammaIdx).toBeGreaterThan(betaIdx);
  });

  it("renders the subtitle under the H1 when provided", () => {
    const html = renderLeakReportHtml({
      title: "T",
      subtitle: "scheme=DemoApp destination=iPhone11",
      sections: [makeSection()],
    });
    expect(html).toContain("scheme=DemoApp destination=iPhone11");
  });

  it("substitutes timestamp and version metadata", () => {
    const html = renderLeakReportHtml({ title: "T", sections: [makeSection()] });
    expect(html).toMatch(/Generated by memorydetective/);
    // ISO 8601 timestamp shape.
    expect(html).toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it("renders a leak delta with a '+' prefix when positive", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          totals: { baselineLeaks: 1, afterLeaks: 4, leakDelta: 3 },
        }),
      ],
    });
    expect(html).toContain('"n">+3<');
  });

  it("renders a negative leak delta without a forced '+' prefix", () => {
    const html = renderLeakReportHtml({
      title: "T",
      sections: [
        makeSection({
          totals: { baselineLeaks: 4, afterLeaks: 1, leakDelta: -3 },
        }),
      ],
    });
    expect(html).toContain('"n">-3<');
    expect(html).not.toContain('"n">+-3<');
  });
});

describe("writeLeakReportHtml", () => {
  it("persists HTML to the requested path and returns the absolute path", () => {
    const out = joinPath(workDir, "report.html");
    const path = writeLeakReportHtml(out, {
      title: "T",
      sections: [makeSection()],
    });
    expect(path).toBe(out);
    const contents = readFileSync(out, "utf8");
    expect(contents).toContain("<!doctype html>");
    expect(contents).toContain("DemoTests/DemoCase/testThing");
  });
});
