/**
 * Pure parser for Apple MetricKit `.mxdiagnostic` payloads. v1.18 (item #79).
 *
 * MetricKit (`MXMetricManager`) delivers JSON payloads to a developer-readable
 * directory on real-device TestFlight / App Store builds. The format is
 * generated by `MXDiagnosticPayload.jsonRepresentation()`:
 *
 * ```jsonc
 * {
 *   "timeStampBegin": "ISO-8601",
 *   "timeStampEnd":   "ISO-8601",
 *   "crashDiagnostics":            [ MXCrashDiagnostic, ... ],
 *   "hangDiagnostics":             [ MXHangDiagnostic, ... ],
 *   "cpuExceptionDiagnostics":     [ MXCPUExceptionDiagnostic, ... ],
 *   "diskWriteExceptionDiagnostics": [ MXDiskWriteExceptionDiagnostic, ... ]
 * }
 * ```
 *
 * Apple does not publish a schema. ChimeHQ/Meter (the canonical community
 * parser, ~222 stars on GitHub) is the de-facto reference. This module is
 * the TypeScript counterpart, deliberately TOLERANT:
 *
 *  - Unknown top-level keys pass through (Apple has silently added fields
 *    between iOS minors).
 *  - `hangDuration`, `totalCPUTime`, `writesCaused` come as LOCALIZED
 *    STRINGS (e.g. `"5.4 sec"`, `"20秒"`, `"1.2 GB"`). We extract the
 *    leading number with a regex; never `parseFloat` the whole string.
 *  - Missing diagnostic arrays are treated as empty, not as errors.
 *  - `payload.version` (per-diagnostic) is echoed in the analyzer result so
 *    a future caller can branch on a schema bump without us shipping a new
 *    type.
 *
 * The parser is split from the analyzer for the same reason `xctraceXml` is
 * separate from the trace analyzers: pure functions, no node:fs / node:child_process,
 * trivially testable.
 */

export interface MetricKitFrame {
  binaryUUID?: string;
  binaryName?: string;
  offsetIntoBinaryTextSegment?: number;
  address?: number;
  sampleCount?: number;
  subFrames?: MetricKitFrame[];
  /** Pass-through for anything Apple ships that we don't model yet. */
  raw?: unknown;
}

export interface MetricKitCallStackTree {
  callStacks: Array<{
    threadAttributed?: boolean;
    callStackRootFrames: MetricKitFrame[];
  }>;
}

export interface MetricKitDiagnostic {
  version?: string;
  callStackTree: MetricKitCallStackTree;
  diagnosticMetaData: Record<string, unknown>;
}

export interface MetricKitPayload {
  timeStampBegin?: string;
  timeStampEnd?: string;
  crashDiagnostics: MetricKitDiagnostic[];
  hangDiagnostics: MetricKitDiagnostic[];
  cpuExceptionDiagnostics: MetricKitDiagnostic[];
  diskWriteExceptionDiagnostics: MetricKitDiagnostic[];
  /** Anything we did not model — Apple has been adding fields silently. */
  raw?: Record<string, unknown>;
}

/**
 * Parse a single `.mxdiagnostic` JSON string into a normalized payload.
 * Missing arrays default to `[]`, missing scalars stay `undefined`.
 * Throws only on invalid JSON. Throwing on a known-shape mismatch would
 * defeat the whole point of the tolerant design.
 */
export function parseMetricKitPayload(jsonText: string): MetricKitPayload {
  let raw: unknown;
  try {
    raw = JSON.parse(jsonText);
  } catch (err) {
    throw new Error(
      `Failed to parse .mxdiagnostic as JSON: ${(err as Error).message}`,
    );
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new Error("Expected .mxdiagnostic top-level to be a JSON object");
  }
  const r = raw as Record<string, unknown>;
  return {
    timeStampBegin: asStringOrUndefined(r.timeStampBegin),
    timeStampEnd: asStringOrUndefined(r.timeStampEnd),
    crashDiagnostics: asDiagnosticArray(r.crashDiagnostics),
    hangDiagnostics: asDiagnosticArray(r.hangDiagnostics),
    cpuExceptionDiagnostics: asDiagnosticArray(r.cpuExceptionDiagnostics),
    diskWriteExceptionDiagnostics: asDiagnosticArray(
      r.diskWriteExceptionDiagnostics,
    ),
    raw: r,
  };
}

function asStringOrUndefined(v: unknown): string | undefined {
  return typeof v === "string" ? v : undefined;
}

function asDiagnosticArray(v: unknown): MetricKitDiagnostic[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((d): d is Record<string, unknown> => typeof d === "object" && d !== null)
    .map((d) => ({
      version: asStringOrUndefined(d.version),
      callStackTree: parseCallStackTree(d.callStackTree),
      diagnosticMetaData:
        typeof d.diagnosticMetaData === "object" && d.diagnosticMetaData !== null
          ? (d.diagnosticMetaData as Record<string, unknown>)
          : {},
    }));
}

function parseCallStackTree(v: unknown): MetricKitCallStackTree {
  if (typeof v !== "object" || v === null) return { callStacks: [] };
  const callStacks = (v as { callStacks?: unknown }).callStacks;
  if (!Array.isArray(callStacks)) return { callStacks: [] };
  return {
    callStacks: callStacks
      .filter((s): s is Record<string, unknown> => typeof s === "object" && s !== null)
      .map((s) => ({
        threadAttributed:
          typeof s.threadAttributed === "boolean" ? s.threadAttributed : undefined,
        callStackRootFrames: parseFrames(s.callStackRootFrames),
      })),
  };
}

function parseFrames(v: unknown): MetricKitFrame[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((f): f is Record<string, unknown> => typeof f === "object" && f !== null)
    .map((f) => ({
      binaryUUID: asStringOrUndefined(f.binaryUUID),
      binaryName: asStringOrUndefined(f.binaryName),
      offsetIntoBinaryTextSegment:
        typeof f.offsetIntoBinaryTextSegment === "number"
          ? f.offsetIntoBinaryTextSegment
          : undefined,
      address: typeof f.address === "number" ? f.address : undefined,
      sampleCount:
        typeof f.sampleCount === "number" ? f.sampleCount : undefined,
      subFrames: parseFrames(f.subFrames),
      raw: f,
    }));
}

/**
 * Extract the top (deepest-most-sampled) frame label from a diagnostic.
 *
 * Strategy: pick the first `callStacks[0].callStackRootFrames[0]` that has
 * a `binaryName`. Fall back to `binaryName + 0x<offset hex>` for
 * unsymbolicated frames. Returns `"<unknown>"` when the stack is empty —
 * we do not silently elide diagnostics with missing stacks because their
 * count still matters for aggregation.
 */
export function extractTopFrameLabel(d: MetricKitDiagnostic): string {
  const root = d.callStackTree.callStacks[0]?.callStackRootFrames[0];
  if (!root) return "<unknown>";
  const name = root.binaryName;
  if (!name) return "<unknown>";
  // We do NOT have symbol names from MetricKit by design — that's what
  // dSYM symbolication would add (Phase 8 v1.9, deferred to a future tool).
  // For now, `binaryName + 0x<offset>` is the best we can do without dSYM.
  if (root.offsetIntoBinaryTextSegment != null) {
    return `${name} 0x${root.offsetIntoBinaryTextSegment.toString(16)}`;
  }
  return name;
}

/**
 * Extract the leading number from a localized hang-duration / CPU-time /
 * disk-bytes string. MetricKit ships values like:
 *
 *   "5.4 sec"   "20秒" (Japanese)   "1.2 GB"   "500 ms"   "80 %"
 *
 * Strategy: capture the first numeric run (with optional decimal). Unit
 * inference is best-effort — caller passes the expected unit family
 * (`"ms" | "MB"`) and we convert. Returns `undefined` when no number is
 * present (Apple has shipped malformed strings too).
 */
export function extractLeadingNumber(s: string): number | undefined {
  const m = s.match(/(-?\d+(?:\.\d+)?)/);
  if (!m) return undefined;
  const n = parseFloat(m[1]);
  return Number.isFinite(n) ? n : undefined;
}

/**
 * Convert a MetricKit time string ("5.4 sec", "500 ms", "20秒") to
 * milliseconds. Unknown units default to seconds (the iOS / Japanese
 * default) per Apple's typical output.
 */
export function metricKitTimeToMs(s: string): number | undefined {
  const n = extractLeadingNumber(s);
  if (n == null) return undefined;
  const lower = s.toLowerCase();
  if (lower.includes("ms") || lower.includes("millisec")) return n;
  if (lower.includes("min")) return n * 60_000;
  if (lower.includes("hr") || lower.includes("hour")) return n * 3_600_000;
  // "sec" / Japanese 秒 / unknown -> seconds default.
  return n * 1000;
}

/**
 * Convert a MetricKit disk string ("1.2 GB", "500 MB", "12 KB") to MB.
 * Unknown units default to bytes (rare but safer than dropping the value).
 */
export function metricKitDiskToMB(s: string): number | undefined {
  const n = extractLeadingNumber(s);
  if (n == null) return undefined;
  const lower = s.toLowerCase();
  if (lower.includes("gb")) return n * 1024;
  if (lower.includes("mb")) return n;
  if (lower.includes("kb")) return n / 1024;
  if (lower.includes("byte") || lower.includes(" b")) return n / 1_048_576;
  return n; // assume MB
}
