/**
 * `cleanup_traces`: preview and delete `.trace` bundles generated by
 * `recordTimeProfile`.
 *
 * `.trace` bundles are directories that xctrace writes (typically tens
 * to hundreds of MB each). After a few profiling sessions the
 * `TRACE_ROOT` directory accumulates them quickly, and there is no
 * built-in clean-up in v1.8. This tool gives the agent a single call
 * to triage what is there and remove old runs once they are no longer
 * needed.
 *
 * Defaults err on the safe side:
 *
 * - `dryRun: true` by default. The agent has to explicitly pass
 *   `dryRun: false` to actually delete. Operating with dry-run on by
 *   default means an accidental call surfaces what would be deleted
 *   rather than nuking the disk.
 *
 * - Scope is restricted to `MEMORYDETECTIVE_TRACE_ROOT` by default
 *   (auto-discovered via `getSecurityFlags()`). To clean up traces in
 *   an arbitrary directory, the caller passes `root: <path>` AND sets
 *   `MEMORYDETECTIVE_ALLOW_EXTERNAL_CLEANUP=1` in the environment.
 *   Without the env var, the tool returns `ok: false` with a clear
 *   explanation and the requested path, but deletes nothing.
 *
 * - Only directories ending in `.trace` are considered. Files,
 *   non-`.trace` directories, and symlinks are skipped without
 *   recursion past the boundary so the tool cannot accidentally
 *   remove anything outside its declared mandate.
 *
 * Returns `{ candidates, deleted, freedMB }`. Candidates are sorted by
 * `ageDays` descending (oldest first), so the agent can show the user
 * the most-stale traces at the top of the list.
 */

import { z } from "zod";
import type { Dirent } from "node:fs";
import {
  existsSync,
  readdirSync,
  rmSync,
  statSync,
} from "node:fs";
import {
  isAbsolute as isAbsolutePath,
  join as joinPath,
  resolve as resolvePath,
  sep as pathSep,
} from "node:path";
import { getSecurityFlags } from "../runtime/securityFlags.js";
import { outputFormatField } from "../runtime/responseFormatter.js";

export const cleanupTracesShape = {
  olderThanDays: z
    .number()
    .nonnegative()
    .optional()
    .describe(
      "Only consider `.trace` bundles whose modification time is older than this many days. Omit to consider all traces under the root regardless of age.",
    ),
  dryRun: z
    .boolean()
    .default(true)
    .describe(
      "When `true` (default), the tool returns the list of candidates without deleting. Pass `false` to actually delete. The default-to-true means an accidental call previews instead of destroying.",
    ),
  root: z
    .string()
    .optional()
    .describe(
      "Directory to scan. Defaults to `MEMORYDETECTIVE_TRACE_ROOT`. If the resolved path is outside the configured trace root, the tool requires `MEMORYDETECTIVE_ALLOW_EXTERNAL_CLEANUP=1` in the environment to proceed.",
    ),
  outputFormat: outputFormatField,
} as const;

export const cleanupTracesSchema = z.object(cleanupTracesShape);
export type CleanupTracesInput = z.infer<typeof cleanupTracesSchema>;

export interface CleanupCandidate {
  /** Absolute path to the `.trace` bundle. */
  path: string;
  /** Total bundle size in MB (rounded to one decimal). */
  sizeMB: number;
  /** Age in days since last modification (rounded to one decimal). */
  ageDays: number;
}

export interface CleanupTracesResult {
  ok: boolean;
  dryRun: boolean;
  /** Absolute path actually scanned. Reflects the default when `root` was omitted. */
  root: string;
  /** Total candidates discovered (independent of whether they were deleted). */
  candidates: CleanupCandidate[];
  /** Count of candidates actually deleted. 0 when `dryRun: true`. */
  deleted: number;
  /** Total MB freed by deletions. 0 when `dryRun: true`. */
  freedMB: number;
  /** Present when the call was rejected (e.g. external-root guard). */
  failureReason?: string;
}

/**
 * Pure: build the path-prefix check that determines whether a target
 * lives under the trace-root boundary. Threaded as a helper for
 * testability and to keep the symlink-resolution logic in one place.
 */
export function isInsideTraceRoot(
  candidate: string,
  traceRoot: string,
): boolean {
  const c = resolvePath(candidate);
  const r = resolvePath(traceRoot);
  if (c === r) return true;
  const rWithSep = r.endsWith(pathSep) ? r : r + pathSep;
  return c.startsWith(rWithSep);
}

/**
 * Recursively sum file sizes under a directory. Used to compute the
 * `.trace` bundle's total disk usage for the candidate report.
 *
 * Failure on a single file (permissions, race condition with a
 * concurrent xctrace flush) is non-fatal: the function logs nothing
 * and skips the entry, returning the best-effort total.
 */
function computeDirSizeBytes(dir: string): number {
  let total = 0;
  let entries: Dirent<string>[];
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const p = joinPath(dir, entry.name);
    if (entry.isDirectory()) {
      total += computeDirSizeBytes(p);
    } else if (entry.isFile()) {
      try {
        total += statSync(p).size;
      } catch {
        // Concurrent removal or permission denied: skip.
      }
    }
    // Symlinks ignored: the tool's mandate is bundles produced by
    // xctrace, which do not create symlinks. Following them would
    // open an exfiltration vector.
  }
  return total;
}

/**
 * Walk a root and collect every directory ending in `.trace` that
 * matches the age filter.
 *
 * Crucially: when a `.trace` directory is found, recursion stops at
 * its boundary. xctrace writes structured content INSIDE a .trace
 * bundle (Run1, Form1.template, etc) that we should not treat as
 * nested .trace bundles. Stopping at the boundary also prevents the
 * tool from chasing infinite recursion across symlink loops.
 */
function findTraceBundles(
  root: string,
  ageThresholdMs: number,
  now: number,
): CleanupCandidate[] {
  const candidates: CleanupCandidate[] = [];
  const visit = (dir: string): void => {
    let entries: Dirent<string>[];
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const p = joinPath(dir, entry.name);
      if (entry.name.endsWith(".trace")) {
        try {
          const stat = statSync(p);
          // Clamp negative ageMs to 0. A bundle's mtime can be slightly
          // AFTER `now` (FS write happening between Date.now() capture
          // and statSync) and a negative ageMs would otherwise fail the
          // threshold check below even when no threshold is set.
          const ageMs = Math.max(0, now - stat.mtimeMs);
          // Apply the threshold only when the caller explicitly asked for
          // a minimum age. With ageThresholdMs == 0, include all bundles
          // regardless of how recently they were written.
          const includeBundle = ageThresholdMs > 0 ? ageMs >= ageThresholdMs : true;
          if (includeBundle) {
            const sizeBytes = computeDirSizeBytes(p);
            candidates.push({
              path: p,
              sizeMB: Math.round((sizeBytes / 1024 / 1024) * 10) / 10,
              ageDays: Math.round((ageMs / 86_400_000) * 10) / 10,
            });
          }
        } catch {
          // Skip on stat failure.
        }
        // Do not descend INTO a .trace bundle.
        continue;
      }
      visit(p);
    }
  };
  visit(root);
  return candidates;
}

export function cleanupTraces(input: CleanupTracesInput): CleanupTracesResult {
  const security = getSecurityFlags();
  const dryRun = input.dryRun ?? true;
  const traceRootResolved = resolvePath(security.traceRoot);
  const root = input.root
    ? isAbsolutePath(input.root)
      ? resolvePath(input.root)
      : resolvePath(input.root)
    : traceRootResolved;

  // External-cleanup guard: when the resolved root is outside the
  // configured TRACE_ROOT, require explicit env opt-in. This is the
  // counterpart to ALLOW_LAUNCH for bootAndLaunchForLeakInvestigation,
  // applied to destructive disk operations.
  if (!isInsideTraceRoot(root, traceRootResolved)) {
    if (process.env.MEMORYDETECTIVE_ALLOW_EXTERNAL_CLEANUP !== "1") {
      return {
        ok: false,
        dryRun,
        root,
        candidates: [],
        deleted: 0,
        freedMB: 0,
        failureReason:
          `cleanup root '${root}' is outside MEMORYDETECTIVE_TRACE_ROOT ('${traceRootResolved}'). ` +
          `Set MEMORYDETECTIVE_ALLOW_EXTERNAL_CLEANUP=1 to proceed against the external path. ` +
          `Default-deny on destructive disk operations outside the configured boundary.`,
      };
    }
  }

  if (!existsSync(root)) {
    return {
      ok: true,
      dryRun,
      root,
      candidates: [],
      deleted: 0,
      freedMB: 0,
    };
  }

  const now = Date.now();
  const ageThresholdMs =
    input.olderThanDays != null
      ? input.olderThanDays * 86_400_000
      : 0;

  const candidates = findTraceBundles(root, ageThresholdMs, now);
  // Oldest first, so the user sees the most-stale traces at the top.
  candidates.sort((a, b) => b.ageDays - a.ageDays);

  let deleted = 0;
  let freedBytes = 0;
  if (!dryRun) {
    for (const cand of candidates) {
      try {
        rmSync(cand.path, { recursive: true, force: true });
        deleted += 1;
        freedBytes += cand.sizeMB * 1024 * 1024;
      } catch {
        // Permission denied or concurrent removal: best-effort, count
        // only the ones that succeeded, leave the agent to retry.
      }
    }
  }

  return {
    ok: true,
    dryRun,
    root,
    candidates,
    deleted,
    freedMB: Math.round((freedBytes / 1024 / 1024) * 10) / 10,
  };
}
